// Generated by CoffeeScript 2.3.1
(function() {
  chrome.extension.onRequest.addListener(function(req, sender, callback) {
    var children, height, key, mod, pressedKey, pressedMod, ref, ref1, ref2, ref3, shortcuts, width;
    switch (req.type) {
      case 'openAllInNewWindow':
        children = req.directory.children;
        return chrome.windows.create({
          url: children.shift().url
        }, function(window) {
          return children.forEach(function(child) {
            return chrome.tabs.create({
              url: child.url,
              windowId: window.id,
              selected: false
            });
          });
        });
      case 'keydown':
        shortcuts = JSON.parse(localStorage.shortcuts || '{}');
        if (shortcuts.disable) {
          return;
        }
        mod = ((ref = shortcuts.openBookmarkTreeInNewTab) != null ? ref.modifier : void 0) || 'alt';
        key = ((ref1 = shortcuts.openBookmarkTreeInNewTab) != null ? ref1.key : void 0) || 'b';
        pressedMod = (mod === 'alt' && req.alt) || (mod === 'ctrl' && req.ctrl) || (mod === 'meta' && req.meta);
        pressedKey = String.fromCharCode(req.key).toLowerCase() === key;
        if (pressedMod && pressedKey) {
          chrome.tabs.create({
            url: chrome.extension.getURL('browser_action.html?full')
          });
        }
        mod = ((ref2 = shortcuts.openBookmarkTreeInNewWindow) != null ? ref2.modifier : void 0) || 'alt';
        key = ((ref3 = shortcuts.openBookmarkTreeInNewWindow) != null ? ref3.key : void 0) || 'w';
        pressedMod = (mod === 'alt' && req.alt) || (mod === 'ctrl' && req.ctrl) || (mod === 'meta' && req.meta);
        pressedKey = String.fromCharCode(req.key).toLowerCase() === key;
        if (pressedMod && pressedKey) {
          width = parseInt(localStorage.width) || 300;
          height = parseInt(localStorage.height) || 400;
          return window.open(chrome.extension.getURL('browser_action.html?full'), '', `width=${width}, height=${height}`);
        }
    }
  });

}).call(this);
